<?php
/**
 * Created by PhpStorm.
 * User: Ruslan
 * Date: 05.12.2018
 * Time: 22:38
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class FrontendController extends Controller
{
    public function init()
    {
        if (!Yii::$app->user->isGuest) {
            $auth = \Yii::$app->authManager;
            $simple = $auth->getRole('simple');
            //Связываем роль с пользователем
            try {
                $auth->revokeAll(Yii::$app->user->id);
                $auth->assign($simple, Yii::$app->user->id);
            } catch (\Exception $exception)
            {
                echo 'Ошибка при создании роли'.PHP_EOL;
            }
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}